name: Release

on:
  push:
    tags:
      - '*'

jobs:

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Release build
        run: |
          mvn -Drevision=${{ github.ref_name }} --batch-mode --update-snapshots verify
          mv ./target/kafka-connect-plugins-${{ github.ref_name }}-jar-with-dependencies.jar ./kafka-connect-plugins-${{ github.ref_name }}.jar

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kafka-connect-plugins-${{ github.ref_name }}.jar
